---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: packages
- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined
  tags: packages
# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
  tags: packages

- include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes
